name: First WorkFlow

on:
  schedule:
    - cron: 0/5 * * * *

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dir
        uses: actions/checkout@v3
      - name: Python Shell
        run: print('Hello World!!!')
        shell: python
      - name: PWSH Shell
        run: Get-ChildItem
        shell: pwsh
      - name: Print ENV Varibales
        run: printenv
        shell: bash
