name: artifact check

on: push

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: download image
        run: wget -O image.jpg https://unsplash.com/photos/j2RgHfqKhCM/download?force=true
      - name: upload-image
        uses: actions/upload-artifact@v3.1.0
        with:
          name: my-image
          path: image.jpg
  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: down-image
        uses: actions/download-artifact@v3.0.0
        with:
          name: my-image
          path: my-images/
      - name: list image
        run: ls -la my-images/
