name: First WorkFlow

on:
  workflow_dispatch:

env:
  MY_TEST_ENV: 'How is test'
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    #if: ${{ github.event.client_payload.environment == 'dev' }}
    steps:
      - name: 'ENV Varibale Test'
        run: echo $MY_TEST_ENV
      - name: 'ENV Test agin within step'
        env:
          MY_TEST_ENV: 'Variable defined in step'
        run: echo ${{ MY_TEST_ENV }}
