name: First WorkFlow

on:
  - push
  - workflow_dispatch
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    #if: ${{ github.event.client_payload.environment == 'dev' }}
    steps:
      - name: Checkout Dir
        uses: actions/checkout@v3
      - name: Python Shell
        run: print('Hello World!!!')
        shell: python
      - name: PWSH Shell
        run: Get-ChildItem
        shell: pwsh
