name: First WorkFlow

on:
  workflow_dispatch:

env:
  MY_TEST_ENV: 'How is test'
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    #if: ${{ github.event.client_payload.environment == 'dev' }}
    steps:
      - name: 'Checkout Repo'
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "test@example.com"
          git config --global user.name "my_bot"
          git fetch
          git checkout -b main
          git config --global init.defaultBranch main
          git brach --set-upstream-to=origin/main
          git pull
          echo $RANDOM >> random.txt
          git add .
          git commit -m 'add random file'
          git push
