name: container workflow

on:
  workflow_dispatch:

jobs:
  container-wf:
    runs-on: ubuntu-latest
    env:
      MY_VAR: 'Job level var'
    container:
     image: node:14.19-alpine3.16
     env:
       MY_VAR: 'this is myvar'
    steps:
      - name: display node version
        run: |
          node -v
          echo $MY_VAR
          cat /etc/os-release
      - name: container in step
        uses: docker://node:lts-buster-slim
        #env:
        #  MY_VAR: 'Varibale in container step'
        with:
          entrypoint: '/bin/printenv'
        
