name: check conditions

on:
  push:
  
jobs:
  myconditions:
    runs-on: ubuntu-latest
    steps:
      -  name: test conditions
         run: |
           eccho ${{ startsWith('Hello', 'He') }}
           eccho ${{ contains('Hello', 'ell') }}
           eccho ${{ endsWith('Hello', 'lo') }}
           eccho ${{ format('Hello {0} {1} {2}', 'World', '!', '!') }}
      - name: test cancel
        if: cancelled()
        run: |
          echo ${{ 'Job was cancelled' }}
      - name: test failure
        if: failure()
        run: |
          echo 'Step was failed'
          
