name: artifact check

on: push

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: download image
        run: wget -O image.jpg https://images.pexels.com/photos/60597/dahlia-red-blossom-bloom-60597.jpeg?cs=srgb&dl=pexels-pixabay-60597.jpg&fm=jpg
      - name: upload-image
        uses: actions/upload-arifact@v3
        with:
          name: my-iamge
          path: image.jpg
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: down-image
        uses: actions/download-artifact@v1
        with:
          name: my-image
          path: my-images/
      - name: list image
        run: ls -la my-images/
