name: First WorkFlow

on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  

jobs:
  my-job:
    runs-on: ubuntu-latest
    #if: ${{ github.event.client_payload.environment == 'dev' }}
    steps:
      - name: Checkout Dir
        uses: actions/checkout@v3
      - name: Python Shell
        run: print('Hello World!!!')
        shell: python
      - name: PWSH Shell
        run: Get-ChildItem
        shell: pwsh
      - name: Print Payload Varibales
        run: echo ${{ github.event.client_payload.environment }}
        shell: bash
