name: Matrix check

on: workflow_dispatch

jobs:
  matrix-check-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node_version: [6, 8, 10]
        include:
          - node_version: 8
            os: macos-latest
            is-this-mac: 'true'
        exclude:
          - node_version: 10
            os: ubuntu-latest
      fail-fast: true
      max-parallel: 2
    steps:
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Echo Node Version
        run: |
          node -v
          echo ${{ matrix.is-this-mac }}
