name: container workflow

on:
  workflow_dispatch:

jobs:
  container-wf:
    runs-on: node:14.19-alpine3.16
    env:
      MY_VAR: 'Job level var'
    #container:
    # image: node:14.19-alpine3.16
    #  env:
    #    MY_VAR: 'this is myvar'
    steps:
      - name: display node version
        run: |
          node -v
          echo $MY_VAR
        
