name: container workflow

on:
  workflow_dispatch:

jobs:
  container-wf:
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine3.16
      env:
        MY_VAR: 'this is myvar'
    steps:
      - name: display node version
        run: |
          node -v
          echo $MY_VAR
        
